# Generated by Django 5.0.6 on 2026-01-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_alter_user_modalidad_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_revisor',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene permisos de Revisor para el módulo de Revisoría.'),
        ),
    ]
