# Generated by Django 5.0.6 on 2026-01-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_revisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_revisor',
        ),
        migrations.AddField(
            model_name='user',
            name='revisor_fiscal',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene permisos de Revisor Fiscal.'),
        ),
    ]
