# Generated by Django 5.0.6 on 2026-01-19 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_revisor_user_revisor_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socio',
            field=models.BooleanField(default=False, help_text='Define si el Jefe de Auditoría tiene privilegios de socio (puede crear usuarios).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='revisor_fiscal',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene acceso al módulo de Revisoría Fiscal.'),
        ),
        migrations.CreateModel(
            name='RegistroInvitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
