# Generated by Django 5.0.6 on 2026-02-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_socio_alter_user_revisor_fiscal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auditor_slots',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad máxima de auditores que el administrador puede crear en modalidad grupal.'),
        ),
    ]
