# Generated by Django 5.0.6 on 2026-02-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_auditor_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auditor_slots',
            field=models.PositiveIntegerField(default=3, help_text='Cantidad máxima de auditores permitidos para este jefe de auditoría (modalidad grupal).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modalidad',
            field=models.CharField(choices=[('I', 'Modalidad Individual'), ('G', 'Modalidad Grupal'), ('S', 'Superadmin')], default='I', help_text='I: individual, G: grupal, S: superadmin', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(default='M', help_text='M: mensual, A: anual, D: demo, NT: no tiene', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='socio',
            field=models.BooleanField(default=False, help_text='Indica si el Jefe de Auditoría tiene privilegios de socio para crear usuarios.'),
        ),
    ]
