# Generated by Django 5.0.6 on 2025-10-31 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_remove_balancecuentas_debe_and_more'),
        ('audits', '0003_audit_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Símbolo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('work_paper_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Número de Papel de Trabajo')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_marks', to='audits.audit', verbose_name='Auditoría')),
            ],
            options={
                'verbose_name': 'Marca de Auditoría',
                'verbose_name_plural': 'Marcas de Auditoría',
                'db_table': 'auditoria_auditmark',
                'ordering': ['work_paper_number', 'created_at'],
                'indexes': [models.Index(fields=['audit', 'is_active'], name='auditoria_a_audit_i_4aadcd_idx')],
            },
        ),
    ]
