# Generated by Django 5.0.6 on 2025-11-02 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_auditmark'),
        ('audits', '0003_audit_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditmark',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Validación'),
        ),
        migrations.AddField(
            model_name='auditmark',
            name='matched_file_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Archivo Coincidente'),
        ),
        migrations.AddField(
            model_name='auditmark',
            name='validation_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Validación'),
        ),
        migrations.AddField(
            model_name='auditmark',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'Válido'), ('invalid', 'Inválido'), ('excluded', 'Excluido'), ('unknown', 'Desconocido')], db_index=True, default='unknown', max_length=20, verbose_name='Estado de Validación'),
        ),
        migrations.CreateModel(
            name='WorkPaperValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_paper_input', models.CharField(max_length=200, verbose_name='Work Paper Input')),
                ('validation_result', models.CharField(choices=[('valid', 'Válido'), ('invalid', 'Inválido'), ('excluded', 'Excluido')], max_length=20, verbose_name='Resultado de Validación')),
                ('matched_file', models.CharField(blank=True, max_length=200, null=True, verbose_name='Archivo Coincidente')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('suggestions_json', models.JSONField(blank=True, null=True, verbose_name='Sugerencias (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Validación')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='audits.audit', verbose_name='Auditoría')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_logs', to='auditoria.auditmark', verbose_name='Marca de Auditoría')),
            ],
            options={
                'verbose_name': 'Log de Validación',
                'verbose_name_plural': 'Logs de Validación',
                'db_table': 'auditoria_workpapervalidationlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit', '-created_at'], name='auditoria_w_audit_i_06f335_idx'), models.Index(fields=['validation_result'], name='auditoria_w_validat_e82ee4_idx')],
            },
        ),
    ]
