# Generated by Django 5.0.6 on 2025-11-02 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0008_auditmark_last_validated_at_and_more'),
        ('audits', '0003_audit_moneda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Símbolo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('verification', 'Verificación'), ('calculation', 'Cálculo'), ('documentation', 'Documentación'), ('review', 'Revisión'), ('analysis', 'Análisis'), ('custom', 'Personalizado')], db_index=True, default='custom', max_length=20, verbose_name='Categoría')),
                ('is_system', models.BooleanField(db_index=True, default=False, verbose_name='Símbolo del Sistema')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_symbols', to='audits.audit', verbose_name='Auditoría (para símbolos personalizados)')),
            ],
            options={
                'verbose_name': 'Símbolo de Auditoría',
                'verbose_name_plural': 'Biblioteca de Símbolos',
                'db_table': 'auditoria_symbollibrary',
                'ordering': ['category', 'display_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='TemplateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workbook_name', models.CharField(max_length=200, verbose_name='Nombre del Libro de Trabajo')),
                ('configuration_json', models.JSONField(verbose_name='Configuración Completa (JSON)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorito')),
                ('download_count', models.IntegerField(default=0, verbose_name='Veces Descargado')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Descarga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_configurations', to='audits.audit', verbose_name='Auditoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Configuración de Plantilla',
                'verbose_name_plural': 'Configuraciones de Plantillas',
                'db_table': 'auditoria_templateconfiguration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100, verbose_name='Nombre de Columna')),
                ('column_order', models.IntegerField(verbose_name='Orden de Columna')),
                ('column_width', models.IntegerField(default=15, verbose_name='Ancho de Columna')),
                ('data_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('currency', 'Moneda'), ('percentage', 'Porcentaje')], default='text', max_length=20, verbose_name='Tipo de Datos')),
                ('is_required', models.BooleanField(default=False, verbose_name='Campo Obligatorio')),
                ('template_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='auditoria.templateconfiguration', verbose_name='Configuración de Plantilla')),
            ],
            options={
                'verbose_name': 'Columna de Plantilla',
                'verbose_name_plural': 'Columnas de Plantillas',
                'db_table': 'auditoria_templatecolumn',
                'ordering': ['template_config', 'column_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='auditoria.symbollibrary', verbose_name='Símbolo')),
                ('template_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_symbols', to='auditoria.templateconfiguration', verbose_name='Configuración de Plantilla')),
            ],
            options={
                'verbose_name': 'Símbolo de Plantilla',
                'verbose_name_plural': 'Símbolos de Plantillas',
                'db_table': 'auditoria_templatesymbol',
                'ordering': ['template_config', 'display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='symbollibrary',
            index=models.Index(fields=['category', 'is_active'], name='auditoria_s_categor_200c99_idx'),
        ),
        migrations.AddIndex(
            model_name='symbollibrary',
            index=models.Index(fields=['is_system', 'is_active'], name='auditoria_s_is_syst_2ff5a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='symbollibrary',
            constraint=models.UniqueConstraint(condition=models.Q(('audit__isnull', False)), fields=('symbol', 'audit'), name='unique_symbol_per_audit'),
        ),
        migrations.AddConstraint(
            model_name='symbollibrary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('symbol',), name='unique_system_symbol'),
        ),
        migrations.AddIndex(
            model_name='templateconfiguration',
            index=models.Index(fields=['audit', '-created_at'], name='auditoria_t_audit_i_a2926e_idx'),
        ),
        migrations.AddIndex(
            model_name='templateconfiguration',
            index=models.Index(fields=['created_by', '-created_at'], name='auditoria_t_created_d9ba36_idx'),
        ),
        migrations.AddIndex(
            model_name='templateconfiguration',
            index=models.Index(fields=['is_favorite', '-created_at'], name='auditoria_t_is_favo_88e1ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='templatecolumn',
            constraint=models.UniqueConstraint(fields=('template_config', 'column_order'), name='unique_column_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='templatesymbol',
            constraint=models.UniqueConstraint(fields=('template_config', 'symbol'), name='unique_symbol_per_template'),
        ),
    ]
