# Generated by Django 5.0.6 on 2025-11-18 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0009_symbollibrary_templateconfiguration_templatecolumn_and_more'),
        ('audits', '0003_audit_moneda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditmark',
            name='category',
        ),
        migrations.RemoveField(
            model_name='auditmark',
            name='last_validated_at',
        ),
        migrations.RemoveField(
            model_name='auditmark',
            name='matched_file_name',
        ),
        migrations.RemoveField(
            model_name='auditmark',
            name='validation_message',
        ),
        migrations.RemoveField(
            model_name='auditmark',
            name='validation_status',
        ),
        migrations.AlterField(
            model_name='auditmark',
            name='audit',
            field=models.ForeignKey(help_text='Auditoría a la que pertenece esta marca', on_delete=django.db.models.deletion.CASCADE, related_name='audit_marks', to='audits.audit', verbose_name='Auditoría'),
        ),
        migrations.AlterField(
            model_name='auditmark',
            name='description',
            field=models.TextField(help_text='Descripción de qué significa esta marca', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='auditmark',
            name='symbol',
            field=models.CharField(help_text='Símbolo de la marca (ej: ✓, ◊, ★)', max_length=10, verbose_name='Símbolo'),
        ),
        migrations.AlterField(
            model_name='auditmark',
            name='work_paper_number',
            field=models.CharField(blank=True, db_index=True, help_text='Código del papel de trabajo EN MAYÚSCULAS (ej: SUMARIA CAJAS Y BANCOS)', max_length=50, null=True, verbose_name='Papel de Trabajo'),
        ),
    ]
