# Generated by Django 5.0.6 on 2026-01-15 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0010_remove_unused_auditmark_fields'),
        ('audits', '0004_audit_activa_revisoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisoriaSubcuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=50)),
                ('cuenta_principal', models.CharField(max_length=255)),
                ('nombre_subcuenta', models.CharField(max_length=255)),
                ('saldo_ini_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saldo_julio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saldo_dic_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ajuste_debe', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ajuste_haber', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('saldo_dic_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('es_otras_cuentas', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.audit')),
            ],
        ),
    ]
