# Generated by Django 5.0.6 on 2026-01-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_audit_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='activa_revisoria',
            field=models.BooleanField(default=False, verbose_name='Activar Revisoria'),
        ),
    ]
