# Generated by Django 5.0.6 on 2026-01-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_activitytotaldayspermonth_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditMarks',
        ),
    ]
